title: "GeoExT Workshop Series"
description: "Archive of the ECIR co-located GeoExT Workshops (2023–2025)."
url: "https://geo-ext.github.io"
baseurl: ""

theme: minima
minima:
  skin: solarized

plugins:
  - jekyll-feed
