title: "GeoExT Workshop Series"
tagline: "Geographic Information Extraction from Texts"
description: ""        # 留空，避免页脚显示副标题
url: "https://geo-ext.github.io"
baseurl: ""

theme: minima
minima:
  skin: solarized

plugins:
  - jekyll-feed
