title: "GeoExT"
tagline: ""        # avoid grey duplicate line under the site title
description: ""    # keep empty to prevent extra blocks
url: "https://geo-ext.github.io"
baseurl: ""

theme: minima
minima:
  skin: solarized

plugins:
  - jekyll-feed
