title: "GeoExT Workshop Series"
description: "Official homepage and archive of the GeoExT Workshop Series on Geographic Information Extraction from Texts (GeoExT), co-located with ECIR 2023, 2024, and 2025."
url: "https://geo-ext.github.io/"
baseurl: ""  # 根路径

theme: minima
minima:
  skin: solarized

plugins:
  - jekyll-feed

social_links:
  github: geo-ext
  twitter: geoext_workshop
  email: geoext@dlr.de
